version = 1

exclude_patterns = [
  "**/*.meta",
  "**/*.java",
  "**/*.prefab",
  "**/*.png",
  "**/*.xml",
  "**/*.*.meta",
  "**/*.aar",
  "**/*.json"
]

[[analyzers]]
name = "csharp"

[[transformers]]
name = "dotnet-format"