version = 1

exclude_patterns = [
  "**/*.meta",
  "**/*.prefab",
  "**/*.png",
  "**/*.xml",
  "**/*.*.meta",
  "**/*.aar",
  "**/*.json"
]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "csharp"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "google-java-format"