name: Android Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: game-ci/unity-builder@v4.1.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2021.3.21f1

      - name: Build Android APK
        run: |
          unity -batchmode -quit -projectPath ./YourUnityProject -executeMethod BuildScript.BuildAndroid

# Add deployment or artifact management steps as needed
